version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: simulador-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tfg_simuladorTactico
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3313:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./simuladorTacticas.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./simuladortactico
    container_name: simulador-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tfg_simuladorTactico?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8013:8080"

  frontend:
    build: ./simulador-frontend
    container_name: simulador-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4213:4200"

volumes:
  db_data:

